-- CREATE TABLE `user_info` (
--   `post_id` int(5) NOT NULL AUTO_INCREMENT,
--   `user_state` char(2) NOT NULL,
--   `user_injury` char(2) DEFAULT NULL,
--   `user_comment` varchar(256) DEFAULT NULL,
--   `time` date NOT NULL,
--   `user_id` int(5) DEFAULT NULL,
--   `env` char(2) NOT NULL,
--   PRIMARY KEY (`post_id`)
-- );